[package]
name = "days1"
version = "0.1.0"
authors = ["Toshiki Teramura <toshiki.teramura@gmail.com>"]

[dependencies]
mpi = { git = "https://github.com/rsmpi/rsmpi", rev = "f9aec8b8d82" }

[[bin]]
name = "hello"
path = "src/hello.rs"

[[bin]]
name = "rank"
path = "src/rank.rs"
