version: 2
jobs:
  test:
    docker:
      - image: rust
    steps:
      - checkout
      - run:
          name: Install MPI
          command: |
            apt update
            apt install -y libopenmpi-dev libclang-dev clang libffi-dev texinfo
      - run:
          name: Build All
          command: |
            cargo build --release
      - run:
          name: Day1
          command: |
            mpirun --allow-run-as-root -np 4 ./target/release/day1_hello
            mpirun --allow-run-as-root -np 4 ./target/release/day1_rank

workflows:
  version: 2
  tests:
    jobs:
      - test
